### ISSUE TITLE
AlreadyWrappedError: Room.toString

### ISSUE THREAD

**Issue by wtfrank** [screepers/screeps-profiler#27]
When I use the profiler it seems to go through phases where for a few ticks, it crashes with an AlreadyWrappedError. I added a log statement, and it turns out its complaining about Room.toString.  Then for subsequent ticks it will not through this error.

```
function already wrapped: Room.toString
[12:42:13 PM]screeps-profiler:86
  if (originalFunction.profilerWrapped) { console.log("function already wrapped:", name); throw new AlreadyWrappedError(); }
                                                                                          ^
Error
    at new AlreadyWrappedError (screeps-profiler:10:18)
    at wrapFunction (screeps-profiler:86:97)
    at profileFunction (screeps-profiler:179:10)
    at Object.getOwnPropertyNames.forEach.functionName (screeps-profiler:165:34)
    at Array.forEach (native)
    at profileObjectFunctions (screeps-profiler:124:44)
    at Profiler.prototypes.forEach.proto (screeps-profiler:117:5)
    at Array.forEach (native)
    at hookUpPrototypes (screeps-profiler:116:23)
```

**Comment by gdborton** [comment]
This is basically happening because you're attempting to wrap something that's already being wrapped... It was added as a convenience function to prevent you from double wrapping functions and inflating their numbers.

This is only a bug if it is happening when you aren't calling any of the register functions manually.

**Comment by gdborton** [comment]
@wtfrank are you getting this without calling any of the `.registerX` functions?

**Comment by wtfrank** [comment]
No I am calling some registerX functions (on functions and objects). 

The reason why I suspected it might not be an issue with the way I was using the profiler is because I added  error logging and it was complaining about a core function - Room.toString - rather than a function or object I was attempting to instrument.

This error mainly seems to occur when I'm pushing the CPU limit.

**Comment by gdborton** [comment]
Do you know if you're registering anything that might be wrapping `Room.toString()`?

**Comment by wtfrank** [comment]
I'm not wrapping Room.toString() and it is definitely associated with running out of CPU.

I implemented a spawn governor that stopped spawning creeps if my average cpu usage was getting too high, and didn't see this error for ages. Then on Thursday after the deployment of the shards I ran out of CPU and again today because of a non-terminating loop bug in my code, and I started seeing this error message again for a while after the cpu ran out.

**Comment by shibdib** [comment]
I'm encountering this issue as well. The only time toString occurs in my project is the 2 times it's used in the profiler

**Comment by admon84** [comment]
[@dcolclazier](https://github.com/screepers/screeps-profiler/issues/27#issuecomment-417975628), Make sure that you are calling `profiler.wrap(mainloop)` inside an anonymous function. This ensures that `profiler.wrap(mainloop)` is called each time the loop runs, dynamically wrapping the `mainloop` function. For example:

```javascript
const profiler = require('screeps-profiler');

profiler.enable();

module.exports.loop = function() {
  profiler.wrap(mainloop);
}
```

**Comment by admon84** [comment]
[@wtfrank](https://github.com/screepers/screeps-profiler/issues/27#issue-244842416), We removed the `AlreadyWrappedException` in [v3.0.0](https://github.com/screepers/screeps-profiler/releases/tag/v3.0.0). The profiler now repoints the wrapped function profiler object if it's already a wrapper. Please update to the latest version and let us know if you run into any more issues.
